blog/urls.py
from django.views.generic import TemplateView
from django.urls import path, re_path
from . import views

app_name = 'blog'
urlpatterns = [
	path('', views.post_list, name='list'),
    path('create/', views.post_create),
    path('denied/', TemplateView.as_view(template_name='access_denied.html')),
    path('<int:id>/', views.post_detail, name='detail'),
    path('<int:id>/edit/', views.post_update, name='update'),
    re_path(r'^(?P<id>\d+)/delete/', views.post_delete),
    path('comment/delete/<int:id>/', views.comment_delete),
]

resumesite2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView, RedirectView

from blog.views import homepage, favorites, music_list
from users.views import profile 
from biking.views import map_view, importRides, activity_data
from .views import nostr


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', profile),
    path('blog/', include('blog.urls', namespace='blog')),
	path('', homepage, name='home'),
    path('music/', music_list, name='music'),
    path('about', TemplateView.as_view(template_name='about.html')),
    path('extras/', favorites, name='extras'),
    path('resume/', RedirectView.as_view(url='https://www.linkedin.com/in/anders-juengst-26317b128/', permanent=False)),
    path('projects/', TemplateView.as_view(template_name='projects2.html')),
    path('contact/', TemplateView.as_view(template_name='contact.html')),
    path('coursework/', TemplateView.as_view(template_name='coursework.html')),
    path('engl105/', TemplateView.as_view(template_name='engl105/index.html')),
    path('engl105/personal/', TemplateView.as_view(template_name='engl105/personal.html')),
    path('engl105/science/', TemplateView.as_view(template_name='engl105/science.html')),
    path('engl105/conflict/', TemplateView.as_view(template_name='engl105/conflict.html')),
    path('engl105/reflection/', TemplateView.as_view(template_name='engl105/reflection.html')),
    path('biking/import/', importRides, name='importRides'),
    path('biking/data/', activity_data, name='biking_data'),
    path('bike-map/', map_view, name='biking'),
    path('.well-known/nostr.json', nostr, name='nostr_config'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.contrib.contenttypes.fields import GenericRelation

from hitcount.models import HitCount

from users.models import User


# Create your models here.
class Tag(models.Model):
    title = models.CharField(max_length=64)
    description = models.CharField(max_length=500, blank=True)
    slug = models.SlugField(unique=True)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title


class Post(models.Model):
    title = models.CharField(max_length=200)
    displayPath = models.CharField(max_length=40, default="")
    subtitle = models.CharField(max_length=512, blank=True)
    slug = models.SlugField(unique=True)
    image = models.FileField(null=True, blank=True)
    content = models.TextField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    public = models.BooleanField(default=False)
    isMarkdownContent = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag)
    hit_count_generic = GenericRelation(
        HitCount,
        object_id_field="object_pk",
        related_query_name="hit_count_generic_relation",
    )

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"id": self.id})

    class Meta:
        ordering = ["-timestamp", "-updated"]


class Extra(models.Model):
    title = models.CharField(max_length=400)
    description = models.TextField(blank=True, default="")
    author = models.CharField(blank=True, max_length=100)
    link = models.URLField(blank=True, default="")
    public = models.BooleanField(default=True)
    ARTICLE = "article"
    BOOK = "book"
    MUSIC = "music"
    VIDEO = "video"
    PODCAST = "podcast"
    TEXT = "text"
    MEME = "meme"
    SITE = "site"
    CONTENT_TYPE_CHOICES = [
        (ARTICLE, "article"),
        (BOOK, "book"),
        (MUSIC, "music"),
        (VIDEO, "video"),
        (PODCAST, "podcast"),
        (TEXT, "text"),
        (MEME, "meme"),
        (SITE, "site"),
    ]
    contentType = models.CharField(
        max_length=10,
        choices=CONTENT_TYPE_CHOICES,
        default=TEXT,
    )
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    score = models.IntegerField(default=0)

    class Meta:
        ordering = ("-score", "-created")

    def __str__(self):
        return "Comment by {} on {}".format(self.user, self.post)


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_receiver, sender=Post)

class MusicRelease(models.Model):
    title = models.CharField(max_length=200)
    artist = models.CharField(max_length=200)
    release_date = models.DateField()
    description = models.TextField(blank=True, default="")
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    public = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

class MusicReleaseLink(models.Model):
    music_release = models.ForeignKey(MusicRelease, on_delete=models.CASCADE, related_name="links")
    link = models.URLField(max_length=200)
    platform = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.platform} link to {self.music_release.title}"

class LinktreeItem(models.Model):
    title = models.CharField(max_length=200)
    link = models.URLField(max_length=200)
    description = models.TextField(blank=True, default="")
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    public = models.BooleanField(default=True)

    post = models.ForeignKey('Post', on_delete=models.SET_NULL, null=True, blank=True, related_name='linktree_items')
    extra = models.ForeignKey('Extra', on_delete=models.SET_NULL, null=True, blank=True, related_name='linktree_items')
    music_release = models.ForeignKey('MusicRelease', on_delete=models.SET_NULL, null=True, blank=True, related_name='linktree_items')

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Comment, Post
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = [
			"title",
			"content",
			"image",
			"public",
			"isMarkdownContent",
		]

class CommentForm(forms.ModelForm):
	content = forms.CharField(label='', widget=forms.Textarea(attrs={
		'class': 'form-control', 
		'placeholder': 'Comment', 
		'rows': '4', 
		'cols': '50', 
		'required': True, 
		'maxlength': '1500',
		'onkeyup': 'countChars(this)'
	}))

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.form_method = 'post'
		self.helper.form_class = 'comment-form'
		self.helper.form_action = 'submit_survey'

		self.helper = FormHelper()
		self.helper.add_input(Submit('submit', 'Submit', css_class="bg-primary"))

	class Meta:
		model = Comment
		fields = [
			"content",
		]

	 

templates/access_denied.html
{% extends "base.html" %}
{%load static%}
{%block content %}

<div class="container mt-4">
    <h3>Access Denied. You must be logged in to view this page </h3>
    <button class="me-2 btn btn-outline-primary" type="button" onclick="history.back()">Take me back</button>
</div>

{%endblock content%}

templates/breadcrumbs.html
<ul class="custom-breadcrumbs">
    {% for url, label in breadcrumbs %}
        <li>
            {% ifnotequal forloop.counter breadcrumbs_total %}
                <a href="{{ url }}">{{ label|safe }}</a><span class="">/</span>
            {% else %}
                {{ label|safe }}
            {% endifnotequal %}
        </li>
    {% endfor %}
</ul>

templates/comment_deleted.html
<div class="comment card py-3 px-4 mb-3 bg-light">
    <div class="comment-header">
        <div class="comment-author text-muted fst-italic">
            Comment by {{ user_display_name }} ({{ created|date:"N dS, Y" }}) deleted.
        </div>
    </div>
</div>

templates/comment_new.html
{% include "comment.html" with comment=comment %}

templates/extra.html
<div class="col-lg-6 offset-lg-3">
<div class="card mb-4">
  <div class="card-body">
    {% load markdownify %}

    {% if extra.contentType == 'text' %}
    <div class="d-flex flex-column justify-content-center">
      <p class="mx-auto">{{ extra.description|markdownify }}</p>
      <div class="mx-auto"><i>-{{ extra.author }}</i></div>
    </div>
    <a href="{{extra.link}}" target="blank">Source</a>

    {% elif extra.contentType == 'book' %}
    <h3 class="card-title"><em>{{ extra.title }}</em></h3>
    <p>{{ extra.description|markdownify }}</p>
    <a href="{{extra.link}}" target="blank">View on Amazon</a>
    {% elif extra.contentType == 'music' %}
    <h3 class="card-title">{{ extra.title }}</h3>
    <p>{{ extra.description|markdownify }}</p>
    <a href="{{extra.link}}" target="blank">Listen on Spotify</a>
    {% elif extra.contentType == 'site' %}
    <h3 class="card-title">{{ extra.title }}</h3>
    <a href="{{extra.link}}" target="blank">{{extra.link}}</a>
    <p>{{ extra.description|markdownify }}</p>
    {% else %}
    <h3 class="card-title">{{ extra.title }}</h3>
    <p>{{ extra.description|markdownify }}</p>
    {% if extra.link %}
    <a href="{{extra.link}}" target="blank">Link</a>
    {% endif %}
    {% endif %}

  </div>
</div>
</div>

templates/extras.html
{% extends 'base.html' %}
{% load django_bootstrap_breadcrumbs %}
{% load static%}
{% block breadcrumbs %}
{{ block.super }}
{% breadcrumb "about" "/about" %}
{% endblock %}
{% block content %}

<div class="container">
    <div class="row mt-4">
        <div class="col-lg-8 offset-lg-2">
            <div class="my-3 mx-auto text-center p-2" style="max-width: 900px;">
                <p class="fs-2">My favorite quotes, music, books and more</p>
            </div>
        </div>
            <div class="container">
                <div class="row">
                    {% for item in queryset1 %}
                    {% include 'extra.html' with extra=item %}
                    {% endfor %}
                    </div>
            </div>
        </div>
        </div>
</div>

{% endblock content %}

templates/home.html
{% extends "base.html" %}
{%load static%}
{%block content %}

<div class="container my-container">
    <div class="row my-3 mx-auto text-center p-2" style="max-width: 900px;">
	    <!-- <h1 class="logo mb-4">Anders Juengst</h1> -->
        <p class="fs-4">Hi! I’m Anders, a Brooklyn based producer, DJ, and engineer.
            Check out my music and writing below. Read more about me <a href="/about">here.</a>
        </p>
    </div>
    <!-- Combined list for small screens -->
    <div class="row d-lg-none">
        <div class="col-md-8 col-sm-12 offset-md-2">
            <h3 class="mb-4">Recent</h3>
            {% for entry in combined_items %}
                {% if entry.type == 'music' %}
                    <div class="card my-4 shadow-sm">
                        <div class="card-body">
                            {% include "music_release_card.html" with music_release=entry.item show_badge=True %}
                        </div>
                    </div>
                {% else %}
                    <div class="card my-4 shadow-sm">
                        <div class="card-body">
                            
                            <div class="card-title">
                                <h3 class="post-title">
                                    <span class="badge bg-primary text-black me-2 mb-1" style="font-size: 0.7rem; vertical-align: middle;">Blog</span><a href="{{entry.item.get_absolute_url}}">{{entry.item.title}}</a>
                                </h3>
                                <div class="mb-2">
                                    <small>{{entry.item.timestamp|date:"m/d/y" }}</small>
                                </div>
                            </div>

                            {% if entry.item.subtitle %}
                                {% if entry.item.isMarkdownContent %}
                                    {% load markdownify %}
                                    {{entry.item.subtitle|markdownify}}
                                {% else %}
                                    <p>{{entry.item.subtitle|linebreaks}}</p>
                                {% endif %}
                            {% else %}
                                <p class="card-text">
                                    {% autoescape off %}
                                    {% if entry.item.isMarkdownContent %}
                                    {% load markdownify %}
                                    {{entry.item.content|markdownify|truncatechars:200}}
                                    {% else %}
                                    {{entry.item.content|linebreaks|truncatechars:200}}
                                    {% endif %}
                                    {% endautoescape %}
                                </p>
                            {% endif %}
                            <!-- <a href="{{entry.item.get_absolute_url}}" class="float-end btn btn-outline-secondary">View</a> -->
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
            <div class="text-center mb-4"><small><a href="/blog/">see more blog posts</a></small></div>
            <div class="border-top my-4"></div>
            <h3>Projects</h3>
            <div class="card my-4 shadow-sm" >
                <div class="card-body">
                        <p><a class="fs-4" href="https://ulti-verse.com" target="_blank">ulti-verse.com</a><br>
                        Searchable index of USA Ultimate tournament, game,
                        and roster data scraped from 2014 to present</p>
                    <a href="/blog/7/" class="float-end btn btn-outline-secondary">Details</a>
                </div>
            </div>
            <div class="card my-4 shadow-sm" >
                <div class="card-body">
                        <p><a class="fs-4" href="https://nostr.how" target="_blank">Nostr.how</a><br>
                        Explanation and onboarding
                        instructions for the Nostr protocol</p>
                    <a href="/blog/9/" class="float-end btn btn-outline-secondary">Details</a>
                </div>
            </div>

        </div>
    </div>

    <!-- Two column layout for large screens -->
    <div class="row d-none d-lg-flex">
        <div class="col-lg-5 offset-lg-1">
            <h3>Music</h3>
            {% for music_release in music_releases %}
                <div class="card my-4 shadow-sm">
                    <div class="card-body">
                        {% include "music_release_card.html" %}
                    </div>
                </div>
            {% endfor %}
            <div class="text-center" style="margin-top: -20px;"><small><a href="/music/">see more</a></small></div>
        </div>

        <div class="col-lg-5">
            <h3>Blog</h3>
            {% for obj in post_list %}
                <div class="card mt-4 shadow-sm">
                    <div class="card-body">
                        <div class="card-title">
                            <h3 class="post-title">
                                <a href="{{obj.get_absolute_url}}">{{obj.title}}</a>
                            </h3>
                            <div class="mb-2">
                                <small>{{obj.timestamp|date:"m/d/y" }}</small>
                            </div>
                        </div>

                        {% if obj.subtitle %}
                            {% if obj.isMarkdownContent %}
                                {% load markdownify %}
                                {{obj.subtitle|markdownify}}
                            {% else %}
                                <p>{{obj.subtitle|linebreaks}}</p>
                            {% endif %}
                        {% else %}
                            <p class="card-text">
                                {% autoescape off %}
                                {% if obj.isMarkdownContent %}
                                {% load markdownify %}
                                {{obj.content|markdownify|truncatechars:200}}
                                {% else %}
                                {{obj.content|linebreaks|truncatechars:200}}
                                {% endif %}
                                {% endautoescape %}
                            </p>
                        {% endif %}
                        <!-- <a href="{{obj.get_absolute_url}}" class="float-end btn btn-outline-secondary">View</a> -->
                    </div>
                </div>
            {% endfor %}
            <div class="text-center mb-4"><small><a href="/blog/">see more</a></small></div>
        </div>

        <div class="col-lg-10 offset-lg-1">
            <div class="border-top my-4"></div>
            <h3>Projects</h3>
            <div class="card my-4 shadow-sm">
                <div class="card-body">
                    <p><a class="fs-4" href="https://ulti-verse.com" target="_blank">ulti-verse.com</a><br>
                    Searchable index of USA Ultimate tournament, game,
                    and roster data scraped from 2014 to present</p>
                    <a href="/blog/7/" class="float-end btn btn-outline-secondary">Details</a>
                </div>
            </div>
            <div class="card my-4 shadow-sm">
                <div class="card-body">
                    <p><a class="fs-4" href="https://musicmap.ders.cloud" target="_blank">NYC Music Map</a><br>
                    Map of NYC electronic music events scraped from RA, sortable by date and genre.</p>
                    <a href="/blog/19/" class="float-end btn btn-outline-secondary">Details</a>
                </div>
            </div>
            <div class="card my-4 shadow-sm">
                <div class="card-body">
                    <p><a class="fs-4" href="https://nostr.how" target="_blank">Nostr.how</a><br>
                    Explanation and onboarding
                    instructions for the Nostr protocol</p>
                    <a href="/blog/9/" class="float-end btn btn-outline-secondary">Details</a>
                </div>
            </div>
        </div>
    </div>
</div>

{%endblock content%}

templates/messages_display.html
{% if messages %}

<div class="alert alert-dark mt-2 alert-dismissible fade show" role="alert">
	{% if messages %}
	<ul class="messages">
		{% for message in messages %}
		<li{% if message.tags %} class="{{message.tags}}"{% endif %}>{{message}}</li>
		{% endfor %}
	</ul>
	{% endif %}
	<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

{% endif %}

templates/music.html
{% extends "base.html" %}
{%load static%}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "music" "/music" %}
{% endblock %}

{% block head_title %} Music | {{block.super}} {%endblock head_title%}

{%block content %}

<div class="container my-container">
    <!-- <div class="row my-3 mx-auto text-center p-2" style="max-width: 900px;">
        <h1>Music</h1>
        <p class="fs-5">Listen to my releases on your favorite platform.</p>
    </div> -->
    <div class="row">
        <div class="col-md-8 col-sm-12 col-lg-6 offset-md-2 offset-lg-3">
            {% for music_release in music_releases %}
                <div class="card my-4 shadow-sm">
                    <div class="card-body">
                        {% include "music_release_card.html" %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{%endblock content%}

templates/post_detail.html
{% extends "base.html" %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "blog" "/blog" %}
    {% breadcrumb instance.displayPath "blog.views.post_detail" instance.id %}
{% endblock %}

{% block head_title %} {{instance.title}} | {{block.super}} {%endblock head_title%}

{%block content %}

{% if user.is_staff %}
<!-- Sticky edit form for admins -->
<div id="sticky-edit-form" style="position: sticky; top: 0; z-index: 1000; background-color: #3f3e3e;">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <div class="p-3">
                    <div class="d-flex justify-content-between align-items-center">
                        <h5 class="mb-0">Edit</h5>
                        <button type="button" id="toggle-form-btn" class="btn btn-sm btn-outline-secondary">
                            <span id="toggle-icon">▶</span>
                        </button>
                    </div>
                    <div id="edit-form-content" style="display: none;">
                        <form id="inline-post-form" enctype="multipart/form-data">
                            {% csrf_token %}

                            <div class="mb-2">
                                <label for="id_title" class="form-label small">Title</label>
                                <input type="text" name="title" value="{{ instance.title }}"
                                       class="form-control form-control-sm" id="id_title" required>
                            </div>

                            <div class="mb-2">
                                <label for="id_content" class="form-label small">Content</label>
                                <textarea name="content" class="form-control form-control-sm" id="id_content"
                                          rows="8" required>{{ instance.content }}</textarea>
                            </div>

                            <div class="row">
                                <div class="col-md-6 mb-2">
                                    <label for="id_image" class="form-label small">Image</label>
                                    <input type="file" name="image" class="form-control form-control-sm" id="id_image" accept="image/*">
                                    {% if instance.image %}
                                    <small class="text-muted">Current: {{ instance.image.name }}</small>
                                    {% endif %}
                                </div>
                                <div class="col-md-6 mb-2">
                                    <div class="form-check mt-4">
                                        <input type="checkbox" name="public" class="form-check-input"
                                               id="id_public" {% if instance.public %}checked{% endif %}>
                                        <label class="form-check-label small" for="id_public">Public</label>
                                    </div>
                                    <div class="form-check">
                                        <input type="checkbox" name="isMarkdownContent" class="form-check-input"
                                               id="id_isMarkdownContent" {% if instance.isMarkdownContent %}checked{% endif %}>
                                        <label class="form-check-label small" for="id_isMarkdownContent">Markdown</label>
                                    </div>
                                </div>
                            </div>

                            <div id="form-errors" class="alert alert-danger alert-sm py-2" style="display: none;"></div>

                            <div class="d-flex gap-2">
                                <button type="submit" class="btn btn-primary btn-sm">
                                    <span class="spinner-border spinner-border-sm" role="status"
                                          aria-hidden="true" id="save-spinner" hidden></span>
                                    Save Changes
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}

<div class="container post">
<div class="row">
<div class="col-lg-8 mx-auto">
<br>
{% if instance.image %}
<img src="{{instance.image.url}}" class="d-block mb-4 rounded mx-auto" style="max-height: 500px;" />
{% endif %}

<header class="d-lg-flex d-block justify-content-between mb-4">
    <div>
        <h1>{{ title }}</h1>
        <div>{% include 'timestamp_tags.html' with post=instance %}</div>
    </div>
</header>
</div>
</div>
{% autoescape off %}
{% if instance.isMarkdownContent %}
<div class="row">
    <div class="col-lg-8 mx-auto">
        {% if has_toc_entries %}
            <strong>In this post:</strong>
            {{ toc }}
        {% endif %}

        {{ content }}

        <div class="related">
            <strong>Related posts:</strong>
            <ul>
            {% for p in related %}
                <li><a href="{{p.get_absolute_url}}">{{ p.title }}</a></li>
            {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% else %}
    <p>{{instance.content|linebreaks}}</p>
{% endif %}

{% endautoescape %}
</div>

<div class="col-lg-8 mx-auto comments-container">
    {% include "comments.html" with comments=comments %}
</div>


</div>

{% if user.is_staff %}
{% load static %}
<script src="{% static 'js/post-edit.js' %}"></script>
{% endif %}

{% endblock content %}

templates/post_form.html
{% extends "base.html" %}

{%block content %}
<h1> Form </h1>

<form method='POST' action='' enctype="multipart/form-data">{% csrf_token %}
{{ form.as_p }}
<input type='submit' value = 'Create Post'>
</form>
{%endblock content%}